nav:
  - Overview: index.md
  - User Guide:
    - Introduction: userguide/index.md
  - Requirements:
    - Introduction: requirements/index.md
    - User Requirements: requirements/user/index.md
    - Functional Requirements: requirements/functional/index.md
  - Hardware:
    - Hardware Overview: hardware/index.md
    - Compute Unit (CU): hardware/nova-cu-v1.md
    - Perception Unit (PU): hardware/nova-pu-v1.md
    - Haptic Band: hardware/nova-band-v1.md
    - Haptic Glove: hardware/nova-glove-v1.md
    - Wearable Sling: hardware/nova-sling-v1.md
  - Software:
    - Software Overview: software/index.md
    - Architecture: software/architecture/index.md
    - Core Software Components:
      - Core Software Components Overview: software/core/index.md
      - Development Environment: software/core/dev-env.md
    - Embedded System Components:
      - Embedded System Components Overview: /software/embedded/index.md
    - Mobile System Components:
      - Mobile System Components Overview: /software/mobile/index.md
    - Website Development:
      - Website Development Overview: /software/web/index.md
    - NOVA CU Installation Guide: software/installation.md
  - Contribute:
    - How to Contribute: contribute/index.md
    - Hardware and Software Roadmap: contribute/roadmap.md
    - Style Guide: contribute/style-guide.md
    - Version Management: contribute/versions.md

  - Ximira Homepage: https://www.ximira.org/



site_name: Ximira Documentation
site_url: https://ximira-org.github.io/docs
repo_url: https://github.com/ximira-org/docs/
edit_uri: edit/main/docs/
extra_css:
  - _assets/extra.css
theme:
  name: material
  logo: _images/ximira-logo.svg
  favicon: _images/favicon.ico
  features:
    - content.action.edit
    - content.action.view
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - toc.follow
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
