nav:
  - Overview: index.md
  - User Guide:
    - Introduction: userguide/index.md
  - System Requirements:
    - Introduction: requirements/index.md
  - Hardware:
    - Hardware Overview: hardware/index.md
    - Compute Unit: hardware/nova-cu-v1.md
    - Haptic Band: hardware/nova-band-v1.md
    - Shoulder Pack: hardware/nova-pack-v1.md
  - Software:
    - Software Overview: software/index.md
  - Contribute:
    - How to Contribute: contribute/index.md

  - Ximira Homepage: https://www.ximira.org/



site_name: Ximira Documentation
site_url: https://ximira-org.github.io/docs
repo_url: https://github.com/ximira-org/docs/
extra_css:
  - _assets/extra.css
theme:
  name: material
  logo: _images/ximira-logo.svg
  favicon: _images/favicon.ico
  features:
    - content.action.edit
    - content.action.view
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - toc.follow
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
